import { Project, ProjectStatus } from './types';

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    region: 'Region III',
    division: 'Bulacan',
    barangay: 'San Rafael',
    schoolId: '101010',
    schoolName: 'San Rafael National High School',
    projectName: 'Construction of 2 Storey 4 Classroom',
    year: 2023,
    batchOfFunds: 'Batch 1',
    projectAllocation: 12500000,
    targetCompletionDate: '2023-12-15',
    actualCompletionDate: '',
    projectId: 'PRJ-2023-001',
    contractId: 'CON-2023-001',
    invitationToBid: '2023-05-01',
    preSubmissionConference: '2023-05-15',
    bidOpening: '2023-05-30',
    resolutionToAward: '2023-06-15',
    noticeToProceed: '2023-07-01',
    contractorName: 'ABC Builders Corp.',
    otherRemarks: 'Slight delay due to rain.',
    statusAsOfDate: '2023-11-01',
    accomplishmentPercentage: 85,
    status: ProjectStatus.Ongoing
  },
  {
    id: '2',
    region: 'NCR',
    division: 'Quezon City',
    barangay: 'Batasan Hills',
    schoolId: '102020',
    schoolName: 'Batasan Hills Elementary School',
    projectName: 'Repair of Roof and Ceiling',
    year: 2024,
    batchOfFunds: 'Batch 2',
    projectAllocation: 5000000,
    targetCompletionDate: '2024-03-30',
    projectId: 'PRJ-2024-055',
    contractId: 'CON-2024-055',
    invitationToBid: '2024-01-10',
    contractorName: 'MegaStructures Inc.',
    statusAsOfDate: '2024-02-15',
    accomplishmentPercentage: 10,
    status: ProjectStatus.Ongoing
  },
  {
    id: '3',
    region: 'Region IV-A',
    division: 'Rizal',
    barangay: 'San Jose',
    schoolId: '103030',
    schoolName: 'Rizal Provincial High School',
    projectName: 'Construction of Science Lab',
    year: 2022,
    batchOfFunds: 'Batch 3',
    projectAllocation: 8000000,
    targetCompletionDate: '2022-11-30',
    actualCompletionDate: '2022-12-05',
    projectId: 'PRJ-2022-112',
    contractId: 'CON-2022-112',
    contractorName: 'BuildRight Solutions',
    statusAsOfDate: '2022-12-05',
    accomplishmentPercentage: 100,
    status: ProjectStatus.Completed
  },
  {
    id: '4',
    region: 'Region I',
    division: 'Ilocos Norte',
    barangay: 'Paoay',
    schoolId: '104040',
    schoolName: 'Paoay Central School',
    projectName: 'Perimeter Fence',
    year: 2024,
    batchOfFunds: 'Batch 1',
    projectAllocation: 2000000,
    targetCompletionDate: '2024-06-01',
    projectId: 'PRJ-2024-099',
    contractId: 'TBD',
    contractorName: 'TBD',
    statusAsOfDate: '2024-01-01',
    accomplishmentPercentage: 0,
    status: ProjectStatus.UnderProcurement
  },
  {
    id: '5',
    region: 'Region VII',
    division: 'Cebu',
    barangay: 'Mabolo',
    schoolId: '105050',
    schoolName: 'Mabolo Elementary School',
    projectName: 'Rehabilitation of Toilets',
    year: 2023,
    batchOfFunds: 'Batch 4',
    projectAllocation: 1500000,
    targetCompletionDate: '2023-10-15',
    projectId: 'PRJ-2023-300',
    contractId: 'CON-2023-300',
    contractorName: 'CleanWater Construction',
    statusAsOfDate: '2023-10-20',
    accomplishmentPercentage: 98,
    status: ProjectStatus.ForFinalInspection
  }
];

export const REGIONS = [
  'NCR', 'Region I', 'Region II', 'Region III', 'Region IV-A', 'Region IV-B',
  'Region V', 'Region VI', 'Region VII', 'Region VIII', 'Region IX', 'Region X',
  'Region XI', 'Region XII', 'CAR', 'CARAGA', 'BARMM'
];
